services:
  postgres:
    image: postgres:17
    container_name: compy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: compy
    ports:
      - "5432:5432"
    volumes:
      - compy-postgres-data:/var/lib/postgresql/data

volumes:
  compy-postgres-data: